cola = []
print("ENTRADA")
cola.append("Juan")
print("Llego:", cola[-1])
cola.append("Alejandra")
print("Llego:", cola[-1])
cola.append("Maria")
print("Llego:", cola[-1])
cola.append("Mario")
print("Llego:", cola[-1])
cola.append("Pepe")
print("Llego:", cola[-1])
print("SALIDA")
atendido = cola.pop(0)
print("Se atendio a:", atendido)
atendido = cola.pop(0)
print("Se atendio a:", atendido)
atendido = cola.pop(0)
print("Se atendio a:", atendido)
atendido = cola.pop(0)
print("Se atendio a:",atendido)
atendido = cola.pop(0)
print("Se atendio a:", atendido)
print(cola)

# Ejercicio del 14 al 17