a = float(input("Ingresa el valor de a:"))
b = float(input("Ingresa el valor de b:"))
c = float(input("Ingresa el valor de c:"))
d = float(input("Ingresa el valor de d:"))
e = float(input("Ingresa el valor de e:"))
f = float(input("Ingresa el valor de f:"))
res = (a+b/c) / (d+e/f)
print(f"Humano aqui esta tu pich... resultado:{res:,.3f}")